// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwfxlmuwsvxrlqkqvyow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3ZnhsbXV3c3Z4cmxxa3F2eW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyMDMwODQsImV4cCI6MjA2ODc3OTA4NH0.S2xdIHYR7aFIN59JuIcf6VcTtB3eTJW79WfWeUljyUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});